"""
run_ablation_studies.py
1. Model A (Baseline): No time-frequency filtering (No-TF) + No cross-view fusion (No-PLMB)
2. Model B (+TF):     With time-frequency filtering (With-TF) + No cross-view fusion (No-PLMB)
3. Model C (+PLMB):   No time-frequency filtering (No-TF) + With cross-view fusion (With-PLMB)
4. Model D (Ours):     With time-frequency filtering (With-TF) + With cross-view fusion (With-PLMB) [Final version]
"""
import os
import subprocess
import json
import numpy as np

RESULTS_SAVE_DIR = "/data/stu1/liuanqi/PFPA-MCE/PFPA-MCE/results/ablation_summary"
os.makedirs(RESULTS_SAVE_DIR, exist_ok=True)

def update_ablation_configs(apply_tf, use_plmb):
    """Dynamically hijack and physically overwrite the ablation logic switches in configuration files and execution scripts"""
    # 1. Dynamically modify the TF filter control key in the data preparation script
    prep_script_path = "./prepare_training_data.py"
    with open(prep_script_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    for idx, line in enumerate(lines):
        if "APPLY_TF_FILTER =" in line:
            lines[idx] = f"APPLY_TF_FILTER = {apply_tf} \n"
            break
    with open(prep_script_path, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    
    # 2. Dynamically modify the PLMB fusion control key in the inference system main.py
    main_script_path = "./main.py"
    with open(main_script_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    for idx, line in enumerate(lines):
        if "USE_PLMB =" in line:
            lines[idx] = f"USE_PLMB = {use_plmb}  # Dynamic ablation switch\n"
            break
    with open(main_script_path, 'w', encoding='utf-8') as f:
        f.writelines(lines)

def run_command(cmd_str):
    print(f"Executing core command: {cmd_str}")
    process = subprocess.Popen(cmd_str, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    for line in process.stdout:
        print(line, end="")
    process.wait()
    if process.returncode != 0:
        print(f"Command execution failed, program aborted: {cmd_str}")
        return False
    return True

def collect_metrics_for_variant(variant_name):
    """Extract core perfusion and consistency metrics from json files generated by each ablation inference run"""
    results_root = "/data/stu1/liuanqi/PFPA-MCE/PFPA-MCE/results"
    # Determine the output file name based on the logic of main.py
    json_file = "final_perfusion_results.json" if "With-PLMB" in variant_name else "no_plmb_results.json"
    json_path = os.path.join(results_root, json_file)
    
    if not os.path.exists(json_path):
        print(f"Result report not found, unable to extract metrics for this variant: {json_path}")
        return None
        
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    # We dynamically read Global parameters from this batch of data, and generate variant snapshots for saving through fast cross-simulation
    summary_path = os.path.join(RESULTS_SAVE_DIR, f"{variant_name}_metrics.json")
    shutil_copy = f"cp {json_path} {summary_path}"
    os.system(shutil_copy)
    print(f"{variant_name} variant metric data archived successfully!")

def main():
    print("=" * 60)
    print("PFPA-MCE Top-tier Journal Full-loop Ablation Study Automated Testing Pipeline Started")
    print("=" * 60)
    
    # Combination 1: Model A (No-TF + No-PLMB)
    print("\n[Variant 1/4] Compiling Model A: No-TF + No-PLMB variant...")
    update_ablation_configs(apply_tf=False, use_plmb=False)
    if run_command("python prepare_training_data.py") and run_command("python train.py") and run_command("python main.py"):
        collect_metrics_for_variant("Model_A_NoTF_NoPLMB")
    
    # Combination 2: Model B (With-TF + No-PLMB)
    print("\n[Variant 2/4] Compiling Model B: With-TF + No-PLMB variant...")
    update_ablation_configs(apply_tf=True, use_plmb=False)
    if run_command("python prepare_training_data.py") and run_command("python train.py") and run_command("python main.py"):
        collect_metrics_for_variant("Model_B_WithTF_NoPLMB")
    
    # Combination 3: Model C (No-TF + With-PLMB)
    print("\n[Variant 3/4] Compiling Model C: No-TF + With-PLMB variant...")
    update_ablation_configs(apply_tf=False, use_plmb=True)
    if run_command("python prepare_training_data.py") and run_command("python train.py") and run_command("python main.py"):
        collect_metrics_for_variant("Model_C_NoTF_WithPLMB")
    
    # Combination 4: Model D (Ours: With-TF + With-PLMB)
    print("\n[Variant 4/4] Compiling the final perfect form Model D: With-TF + With-PLMB...")
    update_ablation_configs(apply_tf=True, use_plmb=True)
    if run_command("python prepare_training_data.py") and run_command("python train.py") and run_command("python main.py"):
        collect_metrics_for_variant("Model_D_Ours_Full")
    
    print("\n" + "=" * 60)
    print("The full set of ablation studies has been completed automatically with one click!")
    print(f"All multi-task variant reports have been fully archived at: {RESULTS_SAVE_DIR}")
    print("Please open each archived json file and directly extract Global ICC and MSE data to fill in Table 4!")
    print("=" * 60)

if __name__ == "__main__":
    main()